/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux kubuntu12 3.2.0-99-virtual #139-Ubuntu SMP Mon Feb 1 23:52:21 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Mon Mar 14 03:33:44 PDT 2016"
#define BUILD_ENV_SRCDIR "/home/projects/R7800-V1.0.0.40_gpl_src/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/samba/source"
#define BUILD_ENV_BUILDDIR "/home/projects/R7800-V1.0.0.40_gpl_src/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/samba/source"
#define BUILD_ENV_USER "paul"
#define BUILD_ENV_HOST "kubuntu12"
#define BUILD_ENV_COMPILER "arm-openwrt-linux-uclibcgnueabi-gcc"
#endif /* _BUILD_ENV_H */
